//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAPIEmDupla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServico()
        {
            this.ServicoPorOS = new HashSet<ServicoPorOS>();
        }
    
        public int IdOS { get; set; }
        public string IdCliente { get; set; }
        public Nullable<System.DateTime> DataContratacao { get; set; }
        public Nullable<System.DateTime> DataExecucao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicoPorOS> ServicoPorOS { get; set; }
    }
}
