//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAPIEmDupla.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class ServicoPorOS
    {
        public int IdSPO { get; set; }
        public int IdOS { get; set; }
        public int IdServico { get; set; }
        public string Numero { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }

        [IgnoreDataMember]
        public virtual OrdemServico OrdemServico { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
